//! Monomorphization pass
//!
//! Walks the typed IR and collects all concrete type instantiations
//! of polymorphic functions. For each unique instantiation, generates
//! a specialized copy with a mangled name and rewrites call sites.

use std::collections::{HashMap, HashSet};
use crate::ast::Span;
use crate::tir::*;
use crate::typechecker::{Checker, ClassInfo};
use crate::types::{Diagnostic, DiagnosticKind, InstHead, Ty, TyVar, TyConstraint, Subst};

/// The message and optional note of a "No instance" error. The note carries a
/// mata-ll-specific hint when the (method, type) pair is a known
/// GHC-vs-mata-ll divergence.
fn no_instance_parts(method: &str, ty: &Ty) -> (String, Option<&'static str>) {
    let msg = format!("No instance for '{}' on type '{}'", method, ty);
    let hint = match method {
        "<>" if matches!(ty, Ty::List(_)) =>
            Some("lists are concatenated with ++ in mata-ll; <> (Semigroup) is only defined for String"),
        ">" | "<" | ">=" | "<=" | "compare" | "max" | "min" if matches!(ty, Ty::Tuple(_)) =>
            Some("tuples have no Ord instance in mata-ll; compare their components individually"),
        _ => None,
    };
    (msg, hint)
}

/// A specialization demand: function name + the concrete type it is
/// instantiated at. Keyed on the structured type — never its Display string —
/// so two distinct types can never collide into one specialization.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
struct SpecKey {
    name: String,
    ty: Ty,
}

/// The outcome of dispatching a class-method use site.
#[derive(Debug)]
enum MethodDispatch {
    /// Resolved to this implementation function.
    Resolved(String),
    /// The class variable is still polymorphic here (or carries a rigid
    /// skolem): dispatch is deferred — to the enclosing specialization, the
    /// dictionary-passing rewrite, or the retained generic fallback copy.
    Deferred,
    /// The class variable is bound to this concrete type, and no instance
    /// exists for it.
    Missing(Ty),
}

pub struct Monomorphizer {
    /// Known polymorphic functions (name -> TFunction)
    poly_fns: HashMap<String, TFunction>,
    /// Set of prelude/built-in names (don't try to specialize these)
    builtins: HashSet<String>,
    /// Collected specializations: SpecKey -> mangled name
    specializations: HashMap<SpecKey, String>,
    /// Generated specialized functions
    generated: Vec<TFunction>,
    /// Typeclass method -> set of class names it belongs to
    class_methods: HashSet<String>,
    /// Instance dispatch table, shared with the typechecker's canonical
    /// registry: (method_name, instance head) -> implementation function.
    /// The head is the structured identity of the instance's target type
    /// (see `InstHead`) — instance selection never looks at Display strings.
    instance_methods: HashMap<(String, InstHead), String>,
    /// Implementations *generated by this pass* for structural types, memoized
    /// per concrete type: (method_name, type) -> generated function name.
    /// E.g. ("show", [Integer]) -> show_LInteger, ("==", (Integer, String)) ->
    /// eq_TupInteger_String. Structurally keyed like everything else.
    generated_impls: HashMap<(String, Ty), String>,
    /// Every mangled name this pass has handed out, with the (base, type) it
    /// stands for. `ty_to_suffix` is readable but NOT injective — `(A_B, C)`
    /// and `(A, B_C)` both suffix to "TupA_B_C" — so two distinct types could
    /// silently share one generated function name (one clobbers the other in
    /// the emitted Lua). Genuine collisions get a deterministic "__2"/"__3"…
    /// disambiguator; non-colliding names are unchanged.
    mangled_names: HashMap<String, (String, Ty)>,
    /// Errors collected during monomorphization, located at the clause
    /// being processed when they arose (see `cur_ctx`/`cur_span`).
    pub errors: Vec<Diagnostic>,
    /// The enclosing definition currently being monomorphized, phrased like
    /// the typechecker's contexts ("definition of 'main'", "clause 2 of 'f'").
    cur_ctx: Option<String>,
    /// Source span of the clause currently being monomorphized. `None` inside
    /// compiler-synthesized clauses (derived instances, generated impls).
    cur_span: Option<Span>,
    /// Functions that use dictionary-passing instead of monomorphization
    dict_passing_fns: HashSet<String>,
    /// Specializations deleted when their function tripped the specialization
    /// limit: purged mangled name -> original function name. Call sites
    /// rewritten to these names BEFORE the limit tripped must be reverted to
    /// the original (generic or dictionary-passing) function in `run` —
    /// otherwise they reference functions that no longer exist.
    purged_specs: HashMap<String, String>,
    /// Typeclass constraints per function (from type signatures)
    fn_constraints: HashMap<String, Vec<TyConstraint>>,
    /// Class definitions (class_name -> ClassInfo)
    classes: HashMap<String, ClassInfo>,
    /// Method name -> class name (reverse lookup)
    method_to_class: HashMap<String, String>,
    /// Locally-bound names (lambda params, let binds, case pattern vars)
    /// that should NOT be resolved as typeclass methods
    locals: HashSet<String>,
    /// Stack of (function name, mangled name) for specializations currently
    /// being generated. A still-polymorphic recursive call inside a
    /// specialization resolves to the top-most matching entry — deterministic
    /// and correct under nested specialization (unlike picking an arbitrary
    /// entry from the `specializations` HashMap).
    gen_stack: Vec<(String, String)>,
}

impl Monomorphizer {
    pub fn new(checker: &Checker) -> Self {
        let mut builtins = HashSet::new();
        // Only mark as builtin functions that DON'T have user-defined instances
        for name in &[
            "putStrLn", "++", "$", ".", "id", "const",
            "flip", "not", "error", "sqrt", "otherwise", "max", "min",
            "+", "-", "*", "/", "==", "/=", "<", ">", "<=", ">=",
            // foldr/foldl are Foldable class methods and length carries a
            // Foldable constraint (all dispatched/specialized), so none of
            // them belong here.
            "&&", "||", "mod", "div", "map", "filter",
            "True", "False", "Just", "Nothing",
            ":", "[]", "head", "tail", "take", "drop", "zipWith", "reverse",
            "engage", "liftIO",
            "hmEmpty", "hmInsert", "hmLookup", "hmDelete",
            "hmSize", "hmKeys", "hmValues", "hmMember", "hmToList",
            "bsEmpty", "bsLength", "bsIndex", "bsSub", "bsSingleton",
            "bsConcat", "bsConcatList", "bsNull", "bsHead", "bsTail", "bsCons", "bsSnoc",
            "bsReplicate", "bsPack", "bsUnpack", "bsMap", "bsFoldl",
            "bsXor", "bsZipWith", "bsToString", "bsFromString",
            "bsGetU16LE", "bsGetU32LE", "bsGetI8", "bsGetI16LE", "bsPutI16LE",
            "runST", "newSTArray", "readSTArray", "writeSTArray",
            "modifySTArray", "stArrayLength", "newSTArrayFromList", "stArrayToList",
        ] {
            builtins.insert(name.to_string());
        }

        // Adopt the typechecker's canonical instance registry: it is already
        // keyed by the structured head of each instance's target type, which
        // is exactly the identity instance dispatch needs.
        let mut class_methods = HashSet::new();
        let mut instance_methods = HashMap::new();

        for ((_class_name, head), inst) in checker.get_instances() {
            for (method_name, mangled) in &inst.method_fns {
                class_methods.insert(method_name.clone());
                instance_methods.insert((method_name.clone(), head.clone()), mangled.clone());
            }
        }

        // Class methods with instances should NOT be in builtins
        // (they need to be resolved to instance methods)
        for m in &class_methods {
            builtins.remove(m);
        }
        // But also remove "show" from builtins since it's commonly a class method
        builtins.remove("show");

        // Build method -> class reverse lookup
        let mut method_to_class = HashMap::new();
        for (class_name, info) in checker.get_classes() {
            for (method_name, _) in &info.methods {
                method_to_class.insert(method_name.clone(), class_name.clone());
            }
        }

        Monomorphizer {
            poly_fns: HashMap::new(),
            builtins,
            specializations: HashMap::new(),
            generated: Vec::new(),
            class_methods,
            instance_methods,
            generated_impls: HashMap::new(),
            mangled_names: HashMap::new(),
            errors: Vec::new(),
            cur_ctx: None,
            cur_span: None,
            dict_passing_fns: HashSet::new(),
            purged_specs: HashMap::new(),
            gen_stack: Vec::new(),
            fn_constraints: checker.get_fn_constraints().clone(),
            classes: checker.get_classes().clone(),
            method_to_class,
            locals: HashSet::new(),
        }
    }

    /// Check the post-monomorphization invariant: no type-directed class
    /// method may remain type-erased at a concrete structured type.
    pub fn verify(&self, module: &TModule) -> Vec<String> {
        crate::verify::check(module, &self.class_methods)
    }

    pub fn run(&mut self, module: TModule) -> TModule {
        // Collect polymorphic user-defined functions
        for func in &module.functions {
            if self.is_polymorphic(&func.ty) && !self.builtins.contains(&func.name) {
                self.poly_fns.insert(func.name.clone(), func.clone());
            }
        }
        // Polymorphic derived/instance methods (e.g. show_Box :: Box a -> String)
        // must be specializable per concrete type too, so `show` on a nested
        // value resolves to the concrete field show instead of the type-erased
        // runtime `show`. The generic copy still serves as the fallback.
        for func in &module.instance_fns {
            if self.is_polymorphic(&func.ty) && !self.builtins.contains(&func.name) {
                self.poly_fns.entry(func.name.clone()).or_insert_with(|| func.clone());
            }
        }

        // Monomorphize instance methods too
        let mut instance_fns: Vec<TFunction> = module.instance_fns.iter()
            .map(|f| self.mono_function(f.clone()))
            .collect();

        // Walk all functions to collect specialization demands
        let functions: Vec<TFunction> = module.functions.iter()
            .map(|f| self.mono_function(f.clone()))
            .collect();

        // Keep all original functions (including polymorphic ones — they serve
        // as fallbacks for calls inside other polymorphic contexts where types
        // aren't resolved). Append generated specializations after.
        let mut result_fns: Vec<TFunction> = functions;
        result_fns.append(&mut self.generated);

        // Revert references to purged specializations. When a function trips
        // the specialization limit mid-pass, call sites monomorphized EARLIER
        // already reference its (now deleted) specializations; point them back
        // at the original function so the dictionary-passing rewrite below —
        // or the retained generic copy — handles them.
        if !self.purged_specs.is_empty() {
            for func in result_fns.iter_mut().chain(instance_fns.iter_mut()) {
                for clause in &mut func.clauses {
                    clause.body = self.revert_purged(clause.body.clone());
                    clause.guards = clause.guards.iter().map(|g| TGuard {
                        condition: self.revert_purged(g.condition.clone()),
                        body: self.revert_purged(g.body.clone()),
                    }).collect();
                    clause.where_binds = clause.where_binds.iter().map(|wb| TLocalDef {
                        name: wb.name.clone(),
                        patterns: wb.patterns.clone(),
                        body: self.revert_purged(wb.body.clone()),
                    }).collect();
                }
            }
        }

        // Rewrite dict-passing functions and their call sites
        if !self.dict_passing_fns.is_empty() {
            let dict_fns: Vec<String> = self.dict_passing_fns.iter().cloned().collect();
            for name in &dict_fns {
                if let Some(pos) = result_fns.iter().position(|f| f.name == *name) {
                    let mut func = result_fns[pos].clone();
                    self.rewrite_dict_passing_fn(&mut func);
                    result_fns[pos] = func;
                }
            }
            // Rewrite call sites in non-dict functions
            for func in &mut result_fns {
                if self.dict_passing_fns.contains(&func.name) { continue; }
                for clause in &mut func.clauses {
                    clause.body = self.rewrite_dict_call_sites(clause.body.clone());
                    clause.where_binds = clause.where_binds.iter().map(|wb| TLocalDef {
                        name: wb.name.clone(),
                        patterns: wb.patterns.clone(),
                        body: self.rewrite_dict_call_sites(wb.body.clone()),
                    }).collect();
                }
            }
            for func in &mut instance_fns {
                for clause in &mut func.clauses {
                    clause.body = self.rewrite_dict_call_sites(clause.body.clone());
                }
            }
        }

        TModule {
            data_defs: module.data_defs,
            functions: result_fns,
            instance_fns,
            has_main: module.has_main,
            exports: module.exports,
            record_accessors: module.record_accessors,
            newtypes: module.newtypes,
        }
    }

    /// The type the CLASS VARIABLE of `method` is bound to at a use site,
    /// found by structurally matching the method's declared type against the
    /// type it is used at. E.g. `fromJSON :: Json -> Either String a` used at
    /// `Json -> Either String Person` binds a := Person.
    ///
    /// This is the typechecker's instance evidence: `use_ty` is the
    /// instantiated method type the typechecker recorded on the TIR node (the
    /// same instantiation its `wanted` constraint was solved at), and the
    /// declared method signature comes from the typechecker's class registry.
    /// The match recovers the exact substitution the checker made, wherever
    /// the class variable sits — first argument, return type, nested, or
    /// higher-kinded (`m a` against `IO b`/`[b]`/`LuaIO s b` via the sugared
    /// cases in `collect_subst_by_name`).
    fn class_var_binding(&self, method: &str, use_ty: &Ty) -> Option<Ty> {
        let class_name = self.method_to_class.get(method)?;
        let info = self.classes.get(class_name)?;
        let (_, decl_ty) = info.methods.iter().find(|(n, _)| n == method)?;
        let mut bindings: HashMap<String, Ty> = HashMap::new();
        Self::collect_subst_by_name(decl_ty, use_ty, &mut bindings);
        bindings.get(&info.type_var).cloned()
    }

    /// Dispatch a class-method use at the method type recorded on its TIR
    /// node. Deterministic: bind the class variable (`class_var_binding`),
    /// then resolve the instance for that binding — no positional guessing.
    fn resolve_method_use(&mut self, method: &str, use_ty: &Ty) -> MethodDispatch {
        let Some(binding) = self.class_var_binding(method, use_ty) else {
            return MethodDispatch::Deferred;
        };
        if !binding.free_vars().is_empty() || Self::contains_skolem(&binding) {
            return MethodDispatch::Deferred;
        }
        match self.resolve_at_type(method, &binding, use_ty) {
            Some(name) => MethodDispatch::Resolved(name),
            None => MethodDispatch::Missing(binding),
        }
    }

    /// Dispatch an infix operator that is a class method. Same as
    /// `resolve_method_use`, with one addition kept from the previous
    /// behavior: at a *still-polymorphic* class-variable binding whose head
    /// constructor is known (e.g. `==` on a `Tree a` field inside the
    /// polymorphic derived `eq_Tree`), dispatch by head — the instance choice
    /// depends only on the head — without specializing anything.
    fn resolve_op_use(&mut self, method: &str, use_ty: &Ty) -> MethodDispatch {
        let Some(binding) = self.class_var_binding(method, use_ty) else {
            return MethodDispatch::Deferred;
        };
        if binding.free_vars().is_empty() && !Self::contains_skolem(&binding) {
            return match self.resolve_at_type(method, &binding, use_ty) {
                Some(name) => MethodDispatch::Resolved(name),
                None => MethodDispatch::Missing(binding),
            };
        }
        // Polymorphic binding: structural eq still specializes by shape
        // (element eq degrades to the raw-equality runtime fallback), other
        // methods dispatch by instance head alone.
        if method == "==" {
            if let Ty::List(elem_ty) = &binding {
                return MethodDispatch::Resolved(self.generate_list_eq(&elem_ty.clone()));
            }
            if Self::is_maybe_type(&binding) {
                let inner = Self::maybe_inner_type(&binding).unwrap();
                return MethodDispatch::Resolved(self.generate_maybe_eq(&inner));
            }
            if let Ty::Tuple(elem_tys) = &binding {
                return MethodDispatch::Resolved(self.generate_tuple_eq(&elem_tys.clone()));
            }
        }
        if let Some(head) = InstHead::of(&binding)
            && let Some(mangled) = self.instance_methods.get(&(method.to_string(), head)) {
                return MethodDispatch::Resolved(mangled.clone());
            }
        MethodDispatch::Deferred
    }

    /// Resolve the implementation of `method` for a CONCRETE class-variable
    /// binding. `use_ty` is the full method type at the use site, needed to
    /// specialize a parameterized instance's still-polymorphic method body.
    ///
    /// Resolution order: implementations this pass already generated for the
    /// exact type; structural implementations for compiler-owned shapes
    /// (lists, tuples, Maybe); then the instance registry by head constructor.
    fn resolve_at_type(&mut self, method: &str, binding: &Ty, use_ty: &Ty) -> Option<String> {
        if let Some(existing) = self.generated_impls.get(&(method.to_string(), binding.clone())) {
            return Some(existing.clone());
        }
        match method {
            "==" => {
                if let Ty::List(elem_ty) = binding {
                    return Some(self.generate_list_eq(&elem_ty.clone()));
                }
                if Self::is_maybe_type(binding) {
                    let inner = Self::maybe_inner_type(binding).unwrap();
                    return Some(self.generate_maybe_eq(&inner));
                }
                if let Ty::Tuple(elem_tys) = binding {
                    return Some(self.generate_tuple_eq(&elem_tys.clone()));
                }
            }
            "show" => {
                if let Ty::Tuple(elem_tys) = binding {
                    return Some(self.generate_tuple_show(&elem_tys.clone()));
                }
                if let Some(name) = self.generate_container_show(binding) {
                    return Some(name);
                }
            }
            _ => {}
        }
        // mata-ll design divergence, kept from the previous resolver: `<>`
        // (Semigroup) is deliberately NOT dispatchable at concrete list types
        // — lists are concatenated with ++ (no_instance_msg carries the note).
        // The built-in `Semigroup [a]` instance exists only so polymorphic
        // Semigroup-constrained bodies keep a resolution (`resolve_op_use`'s
        // head dispatch).
        if matches!(binding, Ty::List(_))
            && self.method_to_class.get(method).is_some_and(|c| c == "Semigroup") {
            return None;
        }
        let head = InstHead::of(binding)?;
        let mangled = self.instance_methods.get(&(method.to_string(), head))?.clone();
        // A parameterized instance's method is itself polymorphic (e.g.
        // ord_compare__Pair, a derived show_Box); its body resolves class
        // methods on FIELDS only once specialized at this use's concrete type.
        if method == "show" {
            Some(self.specialize_derived_show(&mangled, binding))
        } else if mangled != method {
            Some(self.specialize_instance_fn(&mangled, use_ty))
        } else {
            // Resolves to itself (e.g. IO's `>>=`): nothing to rewrite.
            Some(mangled)
        }
    }

    /// True if the type contains a rigid skolem anywhere — dispatch on those
    /// is deferred, exactly like a type variable (rank-2 bodies).
    fn contains_skolem(ty: &Ty) -> bool {
        match ty {
            Ty::Skolem(..) => true,
            Ty::Con(_) | Ty::Var(_) | Ty::Unit | Ty::Promoted(_) => false,
            Ty::Arrow(a, b) | Ty::App(a, b) => Self::contains_skolem(a) || Self::contains_skolem(b),
            Ty::List(a) | Ty::IO(a) | Ty::LuaIO(_, a) | Ty::Forall(_, a) => Self::contains_skolem(a),
            Ty::Tuple(elems) => elems.iter().any(Self::contains_skolem),
        }
    }

    fn is_polymorphic(&self, ty: &Ty) -> bool {
        !ty.free_vars().is_empty()
    }

    /// Check if a type is an IO/ST/LuaIO action (monads handled by codegen's bind chain).
    fn is_action_monad(ty: &Ty) -> bool {
        matches!(ty, Ty::IO(_) | Ty::LuaIO(_, _))
            || matches!(ty, Ty::App(f, _) if matches!(f.as_ref(),
                Ty::App(c, _) if matches!(c.as_ref(), Ty::Con(n) if n == "ST")))
    }

    /// Produce the unique function name for `base` at `ty`. The readable
    /// `ty_to_suffix` encoding is kept, but uniqueness is guaranteed through
    /// `mangled_names`: when a DIFFERENT (base, type) pair already owns the
    /// candidate name, a deterministic "__2"/"__3"… disambiguator is appended
    /// (generation order is deterministic, so so is the numbering).
    fn mangle_name(&mut self, base: &str, ty: &Ty) -> String {
        let stem = format!("{}_{}", base, self.ty_to_suffix(ty));
        let mut candidate = stem.clone();
        let mut k = 1u32;
        loop {
            match self.mangled_names.get(&candidate) {
                None => {
                    self.mangled_names
                        .insert(candidate.clone(), (base.to_string(), ty.clone()));
                    return candidate;
                }
                Some((b, t)) if b == base && t == ty => return candidate,
                Some(_) => {
                    k += 1;
                    candidate = format!("{}__{}", stem, k);
                }
            }
        }
    }

    /// Specialize a derived `show` for a parameterized user data type at a
    /// concrete argument type. The generic `show_Box :: Box a -> String` shows
    /// its fields with the type-erased runtime `show` (which can't recover
    /// constructor names, so nested values print as tuples). Cloning it per
    /// concrete type and re-running monomorphization on the body resolves each
    /// field's `show` to the concrete field type — recursively. Returns `base`
    /// unchanged when there is nothing to specialize (monomorphic type, still
    /// polymorphic, or the polymorphic-recursion guard trips).
    fn specialize_derived_show(&mut self, base: &str, arg_ty: &Ty) -> String {
        if self.is_polymorphic(arg_ty) {
            return base.to_string();
        }
        let fn_ty = Ty::arrow(arg_ty.clone(), Ty::Con("String".into()));
        self.specialize_instance_fn(base, &fn_ty)
    }

    /// Specialize a still-polymorphic instance method (derived or user-written,
    /// e.g. `eq_Box`, `ord_compare__Pair`) at the concrete function type it is
    /// used at. Instance resolution alone only picks the FUNCTION — for a
    /// parameterized instance its body still contains class methods at the
    /// instance's type VARIABLES (`compare _a0 _b0` at type `a`), which the
    /// polymorphic original can never resolve. Cloning it per concrete use
    /// type and re-running monomorphization resolves each field's method at
    /// its concrete type — recursively. Returns `base` unchanged when there is
    /// nothing to specialize (not polymorphic, use type not concrete, or the
    /// polymorphic-recursion guard trips).
    fn specialize_instance_fn(&mut self, base: &str, fn_ty: &Ty) -> String {
        if self.is_polymorphic(fn_ty) || !self.poly_fns.contains_key(base) {
            return base.to_string();
        }
        let key = SpecKey { name: base.to_string(), ty: fn_ty.clone() };
        if let Some(existing) = self.specializations.get(&key) {
            return existing.clone();
        }
        if self.specializations.keys().filter(|k| k.name == base).count() > 16 {
            return base.to_string();
        }
        let mangled = self.mangle_name(base, fn_ty);
        // Insert before generating the body so a recursive field of the same
        // type resolves to this same specialization instead of looping.
        self.specializations.insert(key, mangled.clone());
        if let Some(poly_fn) = self.poly_fns.get(base).cloned() {
            let subst = Self::compute_body_subst(&poly_fn, fn_ty);
            let mut spec_fn = poly_fn.clone();
            spec_fn.name = mangled.clone();
            spec_fn.ty = fn_ty.clone();
            spec_fn.clauses = spec_fn.clauses.into_iter()
                .map(|c| c.apply_subst(&subst))
                .collect();
            spec_fn.specialized = true;
            // Keep the generation stack accurate so a still-polymorphic
            // recursive call inside this body resolves to THIS specialization.
            self.gen_stack.push((base.to_string(), mangled.clone()));
            spec_fn = self.mono_function(spec_fn);
            self.gen_stack.pop();
            self.generated.push(spec_fn);
        }
        mangled
    }

    fn ty_to_suffix(&self, ty: &Ty) -> String {
        match ty {
            Ty::Con(name) => name.clone(),
            Ty::Var(v) => format!("v{}", v.name),
            Ty::Arrow(a, b) => format!("{}T{}", self.ty_to_suffix(a), self.ty_to_suffix(b)),
            Ty::App(a, b) => format!("{}A{}", self.ty_to_suffix(a), self.ty_to_suffix(b)),
            Ty::List(a) => format!("L{}", self.ty_to_suffix(a)),
            Ty::IO(a) => format!("IO{}", self.ty_to_suffix(a)),
            Ty::LuaIO(s, a) => format!("LIO{}_{}", s.name, self.ty_to_suffix(a)),
            Ty::Forall(_, inner) => self.ty_to_suffix(inner),
            Ty::Skolem(name, id) => format!("SK{}_{}", name, id),
            Ty::Unit => "Unit".to_string(),
            Ty::Tuple(elems) => format!("Tup{}", elems.iter().map(|e| self.ty_to_suffix(e)).collect::<Vec<_>>().join("_")),
            Ty::Promoted(name) => format!("P{}", name),
        }
    }

    /// Record a "No instance" error at the clause currently being processed.
    fn push_no_instance(&mut self, method: &str, ty: &Ty) {
        let (msg, hint) = no_instance_parts(method, ty);
        self.errors.push(Diagnostic {
            kind: DiagnosticKind::Other(msg),
            context: self.cur_ctx.clone(),
            span: self.cur_span,
            file: None,
            notes: hint.map(str::to_string).into_iter().collect(),
            baseline: false,
        });
    }

    fn mono_function(&mut self, mut func: TFunction) -> TFunction {
        // Name errors after the function the user wrote: a specialization
        // being generated (top of `gen_stack`) reports as its original.
        let display_name = self.gen_stack.last()
            .filter(|(_, mangled)| *mangled == func.name)
            .map(|(base, _)| base.clone())
            .unwrap_or_else(|| func.name.clone());
        let multi_clause = func.clauses.len() > 1;
        func.clauses = func.clauses.into_iter().enumerate()
            .map(|(idx, c)| {
                let ctx = if multi_clause {
                    format!("clause {} of '{}'", idx + 1, display_name)
                } else {
                    format!("definition of '{}'", display_name)
                };
                // Save/restore: specialization generation re-enters
                // mono_function from inside an enclosing clause.
                let saved_ctx = self.cur_ctx.replace(ctx);
                let saved_span = std::mem::replace(&mut self.cur_span, c.span);
                let result = self.mono_clause(c);
                self.cur_ctx = saved_ctx;
                self.cur_span = saved_span;
                result
            })
            .collect();
        func
    }

    fn mono_clause(&mut self, mut clause: TClause) -> TClause {
        // Add clause pattern-bound variables to locals
        let mut pat_vars = Vec::new();
        for pat in &clause.patterns {
            pat_vars.extend(Self::pattern_vars(pat));
        }
        let new_vars: Vec<_> = pat_vars.iter()
            .filter(|n| !self.locals.contains(*n))
            .cloned().collect();
        for name in &pat_vars {
            self.locals.insert(name.clone());
        }
        clause.body = self.mono_expr(clause.body);
        clause.guards = clause.guards.into_iter().map(|g| TGuard {
            condition: self.mono_expr(g.condition),
            body: self.mono_expr(g.body),
        }).collect();
        clause.where_binds = clause.where_binds.into_iter().map(|ld| TLocalDef {
            name: ld.name,
            patterns: ld.patterns,
            body: self.mono_expr(ld.body),
        }).collect();
        for name in &new_vars {
            self.locals.remove(name);
        }
        clause
    }

    fn pattern_vars(pat: &TPattern) -> Vec<String> {
        match pat {
            TPattern::Var(name, _) => vec![name.clone()],
            TPattern::Wildcard | TPattern::LitPat(_) => vec![],
            TPattern::Constructor { args, .. } => {
                args.iter().flat_map(Self::pattern_vars).collect()
            }
            TPattern::Paren(p) => Self::pattern_vars(p),
            TPattern::Tuple(ps) => ps.iter().flat_map(Self::pattern_vars).collect(),
        }
    }

    fn mono_expr(&mut self, expr: TExpr) -> TExpr {
        // Iterative right-spine processing for bind chains
        enum SpineFrame {
            Bind { ty: Ty, op: String, lhs: TExpr, lambda_ty: Ty, params: Vec<(String, Ty)> },
            Seq { ty: Ty, op: String, lhs: TExpr },
            Let { ty: Ty, binds: Vec<TLocalDef> },
        }

        let mut spine: Vec<SpineFrame> = Vec::new();
        let mut current = expr;

        loop {
            match &current.kind {
                TExprKind::InfixApp { op, lhs, .. } if (op == ">>=" || op == ">>") && Self::is_action_monad(&lhs.ty) => {
                    let ty = current.ty.clone();
                    if let TExprKind::InfixApp { op, lhs, rhs } = current.kind {
                        let rhs_ty = rhs.ty.clone();
                        if op == ">>="
                            && let TExprKind::Lambda { params, body } = rhs.kind {
                                let lhs = self.mono_expr(*lhs);
                                spine.push(SpineFrame::Bind {
                                    ty, op,
                                    lhs,
                                    lambda_ty: rhs_ty,
                                    params,
                                });
                                current = *body;
                                continue;
                            }
                        let lhs = self.mono_expr(*lhs);
                        spine.push(SpineFrame::Seq { ty, op, lhs });
                        current = *rhs;
                        continue;
                    }
                    unreachable!();
                }
                TExprKind::Let { .. } if !spine.is_empty() => {
                    let ty = current.ty.clone();
                    if let TExprKind::Let { binds, body } = current.kind {
                        let binds = binds.into_iter().map(|b| TLocalDef {
                            name: b.name,
                            patterns: b.patterns,
                            body: self.mono_expr(b.body),
                        }).collect();
                        spine.push(SpineFrame::Let { ty, binds });
                        current = *body;
                        continue;
                    }
                    unreachable!();
                }
                _ => break,
            }
        }

        // Process terminal node normally
        let mut result = self.mono_expr_node(current);

        // Reconstruct spine bottom-up
        for frame in spine.into_iter().rev() {
            result = match frame {
                SpineFrame::Bind { ty, op, lhs, lambda_ty, params } => TExpr {
                    kind: TExprKind::InfixApp {
                        op,
                        lhs: Box::new(lhs),
                        rhs: Box::new(TExpr {
                            kind: TExprKind::Lambda { params, body: Box::new(result) },
                            ty: lambda_ty,
                        }),
                    },
                    ty,
                },
                SpineFrame::Seq { ty, op, lhs } => TExpr {
                    kind: TExprKind::InfixApp { op, lhs: Box::new(lhs), rhs: Box::new(result) },
                    ty,
                },
                SpineFrame::Let { ty, binds } => TExpr {
                    kind: TExprKind::Let { binds, body: Box::new(result) },
                    ty,
                },
            };
        }
        result
    }

    fn mono_expr_node(&mut self, expr: TExpr) -> TExpr {
        let ty = expr.ty.clone();
        let kind = match expr.kind {
            TExprKind::Var(ref name) => {
                // 1. Typeclass method dispatch, driven by the instantiated
                // method type the typechecker recorded on this node.
                // Skip if the name is a locally-bound variable (parameter, let,
                // case pattern).
                if self.class_methods.contains(name) && !self.locals.contains(name) {
                    match self.resolve_method_use(name, &ty) {
                        MethodDispatch::Resolved(mangled) => {
                            return TExpr { kind: TExprKind::Var(mangled), ty };
                        }
                        MethodDispatch::Missing(binding) => {
                            self.push_no_instance(name, &binding);
                        }
                        MethodDispatch::Deferred => {}
                    }
                }
                // 2. Check for polymorphic function specialization
                // Handle calls inside specializations: if the type is still
                // polymorphic but we have specialization(s) for this function
                // name, use the most recent one (the recursive/sibling call
                // shares the same concrete type as the enclosing specialization)
                if self.poly_fns.contains_key(name) && !self.locals.contains(name) && !self.dict_passing_fns.contains(name) && self.is_polymorphic(&ty) {
                    // Resolve to the enclosing specialization of this function
                    // (top-most on the generation stack). The HashMap of all
                    // specializations has no meaningful order, so fall back to
                    // the lexically-smallest one only if this call is somehow
                    // not inside a specialization of `name`.
                    let chosen = self.gen_stack.iter().rev()
                        .find(|(n, _)| n == name)
                        .map(|(_, m)| m.clone())
                        .or_else(|| {
                            let mut specs: Vec<String> = self.specializations.iter()
                                .filter(|(k, _)| k.name == *name)
                                .map(|(_, v)| v.clone())
                                .collect();
                            specs.sort();
                            specs.into_iter().next()
                        });
                    if let Some(mangled) = chosen {
                        return TExpr { kind: TExprKind::Var(mangled), ty };
                    }
                }
                if self.poly_fns.contains_key(name) && !self.locals.contains(name) && !self.dict_passing_fns.contains(name) && !self.is_polymorphic(&ty) {
                    let key = SpecKey { name: name.clone(), ty: ty.clone() };
                    let mangled = if let Some(existing) = self.specializations.get(&key) {
                        existing.clone()
                    } else {
                        // Check for polymorphic recursion (too many specializations)
                        let spec_count = self.specializations.keys()
                            .filter(|k| k.name == *name)
                            .count();
                        if spec_count > 16 {
                            // Switch to dictionary-passing for this function.
                            // Purge exactly the specializations OF THIS
                            // function, identified by their recorded mangled
                            // names — never by name prefix, which would also
                            // delete specializations of a sibling `foo_bar`
                            // when `foo` trips the limit.
                            self.dict_passing_fns.insert(name.clone());
                            let purged: HashSet<String> = self.specializations.iter()
                                .filter(|(k, _)| k.name == *name)
                                .map(|(_, v)| v.clone())
                                .collect();
                            self.specializations.retain(|k, _| k.name != *name);
                            self.generated.retain(|f| !purged.contains(&f.name));
                            // Remember what was purged: call sites rewritten
                            // to these names before the limit tripped are
                            // reverted to the original function in `run`.
                            for p in purged {
                                self.purged_specs.insert(p, name.clone());
                            }
                            return TExpr { kind: expr.kind, ty };
                        }
                        let mangled = self.mangle_name(name, &ty);
                        self.specializations.insert(key, mangled.clone());
                        if let Some(poly_fn) = self.poly_fns.get(name).cloned() {
                            let mut spec_fn = poly_fn.clone();
                            spec_fn.name = mangled.clone();
                            // Apply type substitution to body for correct method resolution
                            let subst = Self::compute_body_subst(&poly_fn, &ty);
                            spec_fn.ty = ty.clone();
                            spec_fn.clauses = spec_fn.clauses.into_iter()
                                .map(|c| c.apply_subst(&subst))
                                .collect();
                            spec_fn.specialized = true;
                            self.gen_stack.push((name.clone(), mangled.clone()));
                            spec_fn = self.mono_function(spec_fn);
                            self.gen_stack.pop();
                            self.generated.push(spec_fn);
                        }
                        mangled
                    };
                    TExprKind::Var(mangled)
                } else {
                    expr.kind
                }
            }
            TExprKind::App(func, arg) => {
                // A class method in head position is dispatched by the Var
                // case when `func` is monomorphized — the method node's own
                // type is the full instantiated method type, which determines
                // the class-variable binding regardless of where the class
                // variable sits (argument, result, nested, higher-kinded).
                TExprKind::App(
                    Box::new(self.mono_expr(*func)),
                    Box::new(self.mono_expr(*arg)),
                )
            }
            TExprKind::InfixApp { op, lhs, rhs } => {
                // Typeclass method dispatch on infix operators. The TIR drops
                // the operator's own instantiated type, but it is exactly
                // `lhs.ty -> rhs.ty -> result_ty` — reconstruct it and
                // dispatch the same way as a named method use.
                if (self.class_methods.contains(&op) || (op == "/=" && self.class_methods.contains("==")))
                    && !self.locals.contains(&op) {
                    // For /=, resolve via == (the registered method) and wrap in not later
                    let lookup_op = if op == "/=" { "==".to_string() } else { op.clone() };
                    let use_ty = Ty::fun(&[lhs.ty.clone(), rhs.ty.clone()], ty.clone());

                    let resolved = match self.resolve_op_use(&lookup_op, &use_ty) {
                        MethodDispatch::Resolved(mangled) => Some(mangled),
                        MethodDispatch::Missing(binding) => {
                            self.push_no_instance(&op, &binding);
                            None
                        }
                        MethodDispatch::Deferred => None,
                    };

                    if let Some(mangled) = resolved {
                        // For /= operators, wrap in not
                        if op == "/=" {
                            let mono_lhs = self.mono_expr(*lhs);
                            let mono_rhs = self.mono_expr(*rhs);
                            let eq_call = TExpr {
                                kind: TExprKind::App(
                                    Box::new(TExpr::new(
                                        TExprKind::App(
                                            Box::new(TExpr::new(TExprKind::Var(mangled), Ty::Unit)),
                                            Box::new(mono_lhs),
                                        ),
                                        Ty::Unit,
                                    )),
                                    Box::new(mono_rhs),
                                ),
                                ty: ty.clone(),
                            };
                            return TExpr {
                                kind: TExprKind::App(
                                    Box::new(TExpr::new(TExprKind::Var("not_".to_string()), Ty::Unit)),
                                    Box::new(eq_call),
                                ),
                                ty,
                            };
                        }
                        // If the mangled name matches the operator, keep as InfixApp
                        // (e.g. IO monad's >>= stays >>=)
                        if mangled == op {
                            // fall through to normal InfixApp handling below
                        } else {
                            let mono_lhs = self.mono_expr(*lhs);
                            let mono_rhs = self.mono_expr(*rhs);
                            return TExpr {
                                kind: TExprKind::App(
                                    Box::new(TExpr::new(
                                        TExprKind::App(
                                            Box::new(TExpr::new(TExprKind::Var(mangled), Ty::Unit)),
                                            Box::new(mono_lhs),
                                        ),
                                        Ty::Unit,
                                    )),
                                    Box::new(mono_rhs),
                                ),
                                ty,
                            };
                        }
                    }
                }
                TExprKind::InfixApp {
                    op,
                    lhs: Box::new(self.mono_expr(*lhs)),
                    rhs: Box::new(self.mono_expr(*rhs)),
                }
            }
            TExprKind::Negate(inner) => TExprKind::Negate(Box::new(self.mono_expr(*inner))),
            TExprKind::Lambda { params, body } => {
                let saved_locals: Vec<_> = params.iter()
                    .filter(|(name, _)| !self.locals.contains(name))
                    .map(|(name, _)| name.clone())
                    .collect();
                for (name, _) in &params {
                    self.locals.insert(name.clone());
                }
                let body = Box::new(self.mono_expr(*body));
                for name in &saved_locals {
                    self.locals.remove(name);
                }
                TExprKind::Lambda { params, body }
            }
            TExprKind::If { cond, then_branch, else_branch } => {
                TExprKind::If {
                    cond: Box::new(self.mono_expr(*cond)),
                    then_branch: Box::new(self.mono_expr(*then_branch)),
                    else_branch: Box::new(self.mono_expr(*else_branch)),
                }
            }
            TExprKind::Case { scrutinee, branches } => {
                TExprKind::Case {
                    scrutinee: Box::new(self.mono_expr(*scrutinee)),
                    branches: branches.into_iter().map(|b| {
                        let pat_vars = Self::pattern_vars(&b.pattern);
                        let new_vars: Vec<_> = pat_vars.iter()
                            .filter(|n| !self.locals.contains(*n))
                            .cloned().collect();
                        for name in &pat_vars {
                            self.locals.insert(name.clone());
                        }
                        let result = TCaseBranch {
                            pattern: b.pattern,
                            guards: b.guards.into_iter().map(|g| TGuard {
                                condition: self.mono_expr(g.condition),
                                body: self.mono_expr(g.body),
                            }).collect(),
                            body: self.mono_expr(b.body),
                        };
                        for name in &new_vars {
                            self.locals.remove(name);
                        }
                        result
                    }).collect(),
                }
            }
            TExprKind::Let { binds, body } => {
                let new_names: Vec<_> = binds.iter()
                    .filter(|b| !self.locals.contains(&b.name))
                    .map(|b| b.name.clone())
                    .collect();
                for b in &binds {
                    self.locals.insert(b.name.clone());
                }
                let binds = binds.into_iter().map(|b| TLocalDef {
                    name: b.name, patterns: b.patterns,
                    body: self.mono_expr(b.body),
                }).collect();
                let body = Box::new(self.mono_expr(*body));
                for name in &new_names {
                    self.locals.remove(name);
                }
                TExprKind::Let { binds, body }
            }
            TExprKind::Paren(inner) => TExprKind::Paren(Box::new(self.mono_expr(*inner))),
            TExprKind::Tuple(elems) => TExprKind::Tuple(elems.into_iter().map(|e| self.mono_expr(e)).collect()),
            TExprKind::RecordUpdate { record, updates, num_fields } => TExprKind::RecordUpdate {
                record: Box::new(self.mono_expr(*record)),
                updates: updates.into_iter().map(|(n, idx, e)| (n, idx, self.mono_expr(e))).collect(),
                num_fields,
            },
            TExprKind::OutgoingCallback { callee, arity, run_io } =>
                TExprKind::OutgoingCallback {
                    callee: Box::new(self.mono_expr(*callee)),
                    arity, run_io,
                },
            TExprKind::FfiMaybeArg { value } =>
                TExprKind::FfiMaybeArg { value: Box::new(self.mono_expr(*value)) },
            other => other,
        };
        TExpr { kind, ty }
    }

    /// Resolve the eq function for an element type, generating specialized eq
    /// for structural shapes if needed. Type variables use the generic
    /// raw-equality runtime function.
    fn resolve_elem_eq(&mut self, ty: &Ty) -> String {
        if matches!(ty, Ty::Var(_)) {
            return "__mll_eq".to_string();
        }
        let eq_use_ty = Ty::fun(&[ty.clone(), ty.clone()], Ty::Con("Bool".into()));
        match self.resolve_at_type("==", ty, &eq_use_ty) {
            Some(name) => name,
            None => "__mll_eq".to_string(),
        }
    }

    /// Generate a specialized eq function for a tuple type.
    fn generate_tuple_eq(&mut self, elem_tys: &[Ty]) -> String {
        let tuple_ty = Ty::Tuple(elem_tys.to_vec());
        let mangled = self.mangle_name("eq", &tuple_ty);

        let key = ("==".to_string(), tuple_ty.clone());
        if let Some(existing) = self.generated_impls.get(&key) {
            return existing.clone();
        }
        self.generated_impls.insert(key, mangled.clone());

        // Resolve eq for each element type (recursively generates specialized eq)
        let elem_tys_owned: Vec<Ty> = elem_tys.to_vec();
        let mut elem_eq_names = Vec::new();
        for et in &elem_tys_owned {
            elem_eq_names.push(self.resolve_elem_eq(et));
        }

        // Build body: eq_E1(a[1], b[1]) and eq_E2(a[2], b[2]) and ...
        let bool_ty = Ty::Con("Bool".to_string());
        let a = "_a".to_string();
        let b = "_b".to_string();

        // Encode element eq names in the SpecCall
        let eq_spec = format!("__mll_tuple_eq:{}:{}", elem_tys.len(),
            elem_eq_names.join(","));

        let body = TExpr::new(
            TExprKind::SpecCall {
                original: mangled.clone(),
                specialized: eq_spec,
                args: vec![
                    TExpr::new(TExprKind::Var(a.clone()), tuple_ty.clone()),
                    TExpr::new(TExprKind::Var(b.clone()), tuple_ty.clone()),
                ],
            },
            bool_ty.clone(),
        );

        let func = TFunction {
            name: mangled.clone(),
            ty: Ty::fun(&[tuple_ty.clone(), tuple_ty], bool_ty),
            clauses: vec![TClause {
                span: None,
                patterns: vec![
                    TPattern::Var(a, Ty::Unit),
                    TPattern::Var(b, Ty::Unit),
                ],
                guards: vec![],
                body,
                where_binds: vec![],
            }],
            specialized: true,
            dict_params: vec![],
        };
        self.generated.push(func);
        mangled
    }

    fn generate_list_eq(&mut self, elem_ty: &Ty) -> String {
        let list_ty = Ty::List(Box::new(elem_ty.clone()));
        let mangled = self.mangle_name("eq", &list_ty);

        let key = ("==".to_string(), list_ty.clone());
        if let Some(existing) = self.generated_impls.get(&key) {
            return existing.clone();
        }
        self.generated_impls.insert(key, mangled.clone());

        let elem_ty_owned = elem_ty.clone();
        let elem_eq = self.resolve_elem_eq(&elem_ty_owned);

        let bool_ty = Ty::Con("Bool".to_string());
        let body = TExpr::new(
            TExprKind::SpecCall {
                original: mangled.clone(),
                specialized: format!("__mll_list_eq:{}", elem_eq),
                args: vec![
                    TExpr::new(TExprKind::Var("_a".into()), list_ty.clone()),
                    TExpr::new(TExprKind::Var("_b".into()), list_ty.clone()),
                ],
            },
            bool_ty.clone(),
        );

        let func = TFunction {
            name: mangled.clone(),
            ty: Ty::fun(&[list_ty.clone(), list_ty], bool_ty),
            clauses: vec![TClause {
                span: None,
                patterns: vec![
                    TPattern::Var("_a".into(), Ty::Unit),
                    TPattern::Var("_b".into(), Ty::Unit),
                ],
                guards: vec![], body, where_binds: vec![],
            }],
            specialized: true,
            dict_params: vec![],
        };
        self.generated.push(func);
        mangled
    }

    fn is_maybe_type(ty: &Ty) -> bool {
        matches!(ty, Ty::App(f, _) if matches!(f.as_ref(), Ty::Con(n) if n == "Maybe"))
    }

    fn maybe_inner_type(ty: &Ty) -> Option<Ty> {
        if let Ty::App(f, inner) = ty
            && matches!(f.as_ref(), Ty::Con(n) if n == "Maybe") {
                return Some(*inner.clone());
            }
        None
    }

    fn generate_maybe_eq(&mut self, inner_ty: &Ty) -> String {
        let maybe_ty = Ty::app(Ty::Con("Maybe".into()), inner_ty.clone());
        let mangled = self.mangle_name("eq", &maybe_ty);

        let key = ("==".to_string(), maybe_ty.clone());
        if let Some(existing) = self.generated_impls.get(&key) {
            return existing.clone();
        }
        self.generated_impls.insert(key, mangled.clone());

        let inner_ty_owned = inner_ty.clone();
        let elem_eq = self.resolve_elem_eq(&inner_ty_owned);

        let bool_ty = Ty::Con("Bool".to_string());
        let body = TExpr::new(
            TExprKind::SpecCall {
                original: mangled.clone(),
                specialized: format!("__mll_maybe_eq:{}", elem_eq),
                args: vec![
                    TExpr::new(TExprKind::Var("_a".into()), maybe_ty.clone()),
                    TExpr::new(TExprKind::Var("_b".into()), maybe_ty.clone()),
                ],
            },
            bool_ty.clone(),
        );

        let func = TFunction {
            name: mangled.clone(),
            ty: Ty::fun(&[maybe_ty.clone(), maybe_ty], bool_ty),
            clauses: vec![TClause {
                span: None,
                patterns: vec![
                    TPattern::Var("_a".into(), Ty::Unit),
                    TPattern::Var("_b".into(), Ty::Unit),
                ],
                guards: vec![], body, where_binds: vec![],
            }],
            specialized: true,
            dict_params: vec![],
        };
        self.generated.push(func);
        mangled
    }

    fn generate_container_show(&mut self, ty: &Ty) -> Option<String> {
        match ty {
            Ty::List(elem_ty) =>
                Some(self.generate_threaded_show(ty, elem_ty, "__mll_show_list")),
            // Maybe is type-directed: Just x and x share a runtime rep, so the
            // element show plus the type recover the structure (nil == Nothing).
            Ty::App(f, elem_ty) if matches!(f.as_ref(), Ty::Con(n) if n == "Maybe") =>
                Some(self.generate_threaded_show(ty, elem_ty, "__mll_show_maybe")),
            _ => None,
        }
    }

    /// Generate a `show` wrapper that threads the element show into a runtime
    /// helper (`__mll_show_list` / `__mll_show_maybe`). Shared by the container
    /// arms above so list and Maybe stay in lockstep.
    fn generate_threaded_show(&mut self, ty: &Ty, elem_ty: &Ty, runtime_fn: &str) -> String {
        let mangled = self.mangle_name("show", ty);
        let key = ("show".to_string(), ty.clone());
        if let Some(existing) = self.generated_impls.get(&key) {
            return existing.clone();
        }
        self.generated_impls.insert(key, mangled.clone());

        // Resolve show for the element type
        let elem_show = self.resolve_show_for(elem_ty);

        let str_ty = Ty::Con("String".to_string());
        let param = "_x".to_string();
        let body = TExpr::new(
            TExprKind::SpecCall {
                original: mangled.clone(),
                specialized: format!("{}:{}", runtime_fn, elem_show),
                args: vec![TExpr::new(TExprKind::Var(param.clone()), ty.clone())],
            },
            str_ty.clone(),
        );
        let func = TFunction {
            name: mangled.clone(),
            ty: Ty::arrow(ty.clone(), str_ty),
            clauses: vec![TClause {
                span: None,
                patterns: vec![TPattern::Var(param, Ty::Unit)],
                guards: vec![],
                body,
                where_binds: vec![],
            }],
            specialized: true,
            dict_params: vec![],
        };
        self.generated.push(func);
        mangled
    }

    /// Resolve the show function name for a given type.
    fn resolve_show_for(&mut self, ty: &Ty) -> String {
        let show_use_ty = Ty::arrow(ty.clone(), Ty::Con("String".into()));
        match self.resolve_at_type("show", ty, &show_use_ty) {
            Some(name) => name,
            // Fallback to generic runtime show (primitives, or genuinely
            // unresolved/polymorphic types).
            None => "show".to_string(),
        }
    }

    /// Generate a specialized show function for a tuple type.
    /// show_(Integer, String) produces: function(t) return "(" .. show_Integer(t[1]) .. ", " .. show_String(t[2]) .. ")" end
    fn generate_tuple_show(&mut self, elem_tys: &[Ty]) -> String {
        let tuple_ty = Ty::Tuple(elem_tys.to_vec());
        let mangled = self.mangle_name("show", &tuple_ty);

        // Check if already generated
        let key = ("show".to_string(), tuple_ty.clone());
        if let Some(existing) = self.generated_impls.get(&key) {
            return existing.clone();
        }
        self.generated_impls.insert(key, mangled.clone());

        // Resolve show for each element type. Use the unified resolver so a
        // structured element (list, Maybe, nested tuple, user ADT) gets its
        // specialized show rather than the type-erased generic `show` — which
        // would, e.g., render an empty-list element as "Nothing".
        let elem_show_names: Vec<String> =
            elem_tys.iter().map(|et| self.resolve_show_for(et)).collect();

        // Build body: "(" ++ show_E1(t[1]) ++ ", " ++ show_E2(t[2]) ++ ... ++ ")"
        // We generate this as a chain of InfixApp(++, ...)
        let param_name = "_t".to_string();
        let str_ty = Ty::Con("String".to_string());

        let mut parts: Vec<TExpr> = vec![
            TExpr::new(TExprKind::Lit(TLiteral::Str("(".to_string())), str_ty.clone()),
        ];
        for (i, show_fn) in elem_show_names.iter().enumerate() {
            if i > 0 {
                parts.push(TExpr::new(TExprKind::Lit(TLiteral::Str(", ".to_string())), str_ty.clone()));
            }
            // show_Elem(t[i+1]) — represented as App(Var(show_fn), SpecCall to access field)
            let field_access = TExpr::new(
                TExprKind::SpecCall {
                    original: format!("_t_{}", i),
                    specialized: format!("__mll_tup_get:{}", i + 1),
                    args: vec![TExpr::new(TExprKind::Var(param_name.clone()), tuple_ty.clone())],
                },
                elem_tys[i].clone(),
            );
            let show_call = TExpr::new(
                TExprKind::App(
                    Box::new(TExpr::new(TExprKind::Var(show_fn.clone()), Ty::arrow(elem_tys[i].clone(), str_ty.clone()))),
                    Box::new(field_access),
                ),
                str_ty.clone(),
            );
            parts.push(show_call);
        }
        parts.push(TExpr::new(TExprKind::Lit(TLiteral::Str(")".to_string())), str_ty.clone()));

        // Chain with ++
        let body = parts.into_iter().reduce(|acc, part| {
            TExpr::new(
                TExprKind::InfixApp {
                    op: "<>".to_string(),
                    lhs: Box::new(acc),
                    rhs: Box::new(part),
                },
                str_ty.clone(),
            )
        }).unwrap();

        let func = TFunction {
            name: mangled.clone(),
            ty: Ty::arrow(tuple_ty, str_ty),
            clauses: vec![TClause {
                span: None,
                patterns: vec![TPattern::Var(param_name, Ty::Unit)],
                guards: vec![],
                body,
                where_binds: vec![],
            }],
            specialized: true,
            dict_params: vec![],
        };
        self.generated.push(func);
        mangled
    }

    /// Rewrite every reference to a purged specialization back to the original
    /// function name (see `purged_specs`).
    fn revert_purged(&self, expr: TExpr) -> TExpr {
        let ty = expr.ty.clone();
        let kind = match expr.kind {
            TExprKind::Var(name) => {
                let name = self.purged_specs.get(&name).cloned().unwrap_or(name);
                TExprKind::Var(name)
            }
            TExprKind::App(f, a) => TExprKind::App(
                Box::new(self.revert_purged(*f)),
                Box::new(self.revert_purged(*a)),
            ),
            TExprKind::Lambda { params, body } => TExprKind::Lambda {
                params,
                body: Box::new(self.revert_purged(*body)),
            },
            TExprKind::InfixApp { op, lhs, rhs } => TExprKind::InfixApp {
                op,
                lhs: Box::new(self.revert_purged(*lhs)),
                rhs: Box::new(self.revert_purged(*rhs)),
            },
            TExprKind::Negate(e) => TExprKind::Negate(Box::new(self.revert_purged(*e))),
            TExprKind::Paren(e) => TExprKind::Paren(Box::new(self.revert_purged(*e))),
            TExprKind::If { cond, then_branch, else_branch } => TExprKind::If {
                cond: Box::new(self.revert_purged(*cond)),
                then_branch: Box::new(self.revert_purged(*then_branch)),
                else_branch: Box::new(self.revert_purged(*else_branch)),
            },
            TExprKind::Case { scrutinee, branches } => TExprKind::Case {
                scrutinee: Box::new(self.revert_purged(*scrutinee)),
                branches: branches.into_iter().map(|b| TCaseBranch {
                    pattern: b.pattern,
                    guards: b.guards.into_iter().map(|g| TGuard {
                        condition: self.revert_purged(g.condition),
                        body: self.revert_purged(g.body),
                    }).collect(),
                    body: self.revert_purged(b.body),
                }).collect(),
            },
            TExprKind::Let { binds, body } => TExprKind::Let {
                binds: binds.into_iter().map(|b| TLocalDef {
                    name: b.name,
                    patterns: b.patterns,
                    body: self.revert_purged(b.body),
                }).collect(),
                body: Box::new(self.revert_purged(*body)),
            },
            TExprKind::SpecCall { original, specialized, args } => TExprKind::SpecCall {
                original,
                specialized,
                args: args.into_iter().map(|a| self.revert_purged(a)).collect(),
            },
            TExprKind::Tuple(es) => TExprKind::Tuple(
                es.into_iter().map(|e| self.revert_purged(e)).collect(),
            ),
            TExprKind::DictCall { func_name, dict_args, value_args } => TExprKind::DictCall {
                func_name,
                dict_args: dict_args.into_iter().map(|a| self.revert_purged(a)).collect(),
                value_args: value_args.into_iter().map(|a| self.revert_purged(a)).collect(),
            },
            TExprKind::RecordUpdate { record, updates, num_fields } => TExprKind::RecordUpdate {
                record: Box::new(self.revert_purged(*record)),
                updates: updates.into_iter()
                    .map(|(n, idx, e)| (n, idx, self.revert_purged(e)))
                    .collect(),
                num_fields,
            },
            TExprKind::OutgoingCallback { callee, arity, run_io } =>
                TExprKind::OutgoingCallback {
                    callee: Box::new(self.revert_purged(*callee)),
                    arity, run_io,
                },
            TExprKind::FfiMaybeArg { value } =>
                TExprKind::FfiMaybeArg { value: Box::new(self.revert_purged(*value)) },
            other => other,
        };
        TExpr { kind, ty }
    }

    // --- Dictionary-passing support for polymorphic recursion ---

    /// Compute a substitution mapping ALL free type vars in a function body
    /// to concrete types, using the function type signature as source of truth.
    fn compute_body_subst(poly_fn: &TFunction, concrete_ty: &Ty) -> Subst {
        // Step 1: match function type against concrete type for name-based mappings
        let mut name_map: HashMap<String, Ty> = HashMap::new();
        Self::collect_subst_by_name(&poly_fn.ty, concrete_ty, &mut name_map);

        // Step 2: collect ALL free type vars from body
        let mut all_vars: Vec<TyVar> = Vec::new();
        for clause in &poly_fn.clauses {
            Self::collect_clause_vars(clause, &mut all_vars);
        }

        // Step 3: map each body var to concrete type
        let mut map: HashMap<TyVar, Ty> = HashMap::new();
        Self::collect_subst_exact(&poly_fn.ty, concrete_ty, &mut map);
        for var in &all_vars {
            if map.contains_key(var) { continue; }
            if let Some(concrete) = name_map.get(&var.name) {
                map.insert(var.clone(), concrete.clone());
            }
            // A body variable that appears nowhere in the signature is left
            // alone. Such a variable is genuinely unconstrained (a class
            // constraint over it would have been rejected as ambiguous), so
            // any method use involving it stays deferred to the generic
            // fallback. The old "single type parameter: default every
            // unmapped var to the one concrete type" rule invented types here
            // — that is exactly how a `Monad m`-constrained body once ended up
            // resolving at String.
        }
        Subst::from_map(map)
    }

    fn collect_subst_by_name(pattern: &Ty, concrete: &Ty, map: &mut HashMap<String, Ty>) {
        match (pattern, concrete) {
            (Ty::Var(v), _) => { map.insert(v.name.clone(), concrete.clone()); }
            (Ty::Arrow(pa, pb), Ty::Arrow(ca, cb)) |
            (Ty::App(pa, pb), Ty::App(ca, cb)) => {
                Self::collect_subst_by_name(pa, ca, map);
                Self::collect_subst_by_name(pb, cb, map);
            }
            (Ty::List(pa), Ty::List(ca)) |
            (Ty::IO(pa), Ty::IO(ca)) => Self::collect_subst_by_name(pa, ca, map),
            // A constraint variable applied to an argument (`m a`) matched
            // against a sugared concrete type: IO b binds m := IO, [b] binds
            // m := [], LuaIO s b binds m := LuaIO s. Without these cases a
            // result-only `Monad m` never gets bound here, so its method uses
            // (`pure`, `>>=`) could not be dispatched at the use site.
            // Mirrors the App-vs-IO/List/LuaIO cases in types::unify.
            (Ty::App(pf, pa), Ty::IO(ca)) => {
                Self::collect_subst_by_name(pf, &Ty::Con("IO".into()), map);
                Self::collect_subst_by_name(pa, ca, map);
            }
            (Ty::App(pf, pa), Ty::List(ca)) => {
                Self::collect_subst_by_name(pf, &Ty::Con("[]".into()), map);
                Self::collect_subst_by_name(pa, ca, map);
            }
            (Ty::App(pf, pa), Ty::LuaIO(s, ca)) => {
                let lua_io_s = Ty::App(Box::new(Ty::Con("LuaIO".into())), Box::new(Ty::Var(s.clone())));
                Self::collect_subst_by_name(pf, &lua_io_s, map);
                Self::collect_subst_by_name(pa, ca, map);
            }
            (Ty::Tuple(ps), Ty::Tuple(cs)) if ps.len() == cs.len() => {
                for (p, c) in ps.iter().zip(cs.iter()) {
                    Self::collect_subst_by_name(p, c, map);
                }
            }
            (Ty::Forall(_, pi), _) => Self::collect_subst_by_name(pi, concrete, map),
            _ => {}
        }
    }

    fn collect_subst_exact(pattern: &Ty, concrete: &Ty, map: &mut HashMap<TyVar, Ty>) {
        match (pattern, concrete) {
            (Ty::Var(v), _) => { map.insert(v.clone(), concrete.clone()); }
            (Ty::Arrow(pa, pb), Ty::Arrow(ca, cb)) |
            (Ty::App(pa, pb), Ty::App(ca, cb)) => {
                Self::collect_subst_exact(pa, ca, map);
                Self::collect_subst_exact(pb, cb, map);
            }
            (Ty::List(pa), Ty::List(ca)) |
            (Ty::IO(pa), Ty::IO(ca)) => Self::collect_subst_exact(pa, ca, map),
            // Same sugared-type equivalences as collect_subst_by_name:
            // `m a` vs IO b / [b] / LuaIO s b binds the constructor variable.
            (Ty::App(pf, pa), Ty::IO(ca)) => {
                Self::collect_subst_exact(pf, &Ty::Con("IO".into()), map);
                Self::collect_subst_exact(pa, ca, map);
            }
            (Ty::App(pf, pa), Ty::List(ca)) => {
                Self::collect_subst_exact(pf, &Ty::Con("[]".into()), map);
                Self::collect_subst_exact(pa, ca, map);
            }
            (Ty::App(pf, pa), Ty::LuaIO(s, ca)) => {
                let lua_io_s = Ty::App(Box::new(Ty::Con("LuaIO".into())), Box::new(Ty::Var(s.clone())));
                Self::collect_subst_exact(pf, &lua_io_s, map);
                Self::collect_subst_exact(pa, ca, map);
            }
            (Ty::Tuple(ps), Ty::Tuple(cs)) if ps.len() == cs.len() => {
                for (p, c) in ps.iter().zip(cs.iter()) {
                    Self::collect_subst_exact(p, c, map);
                }
            }
            (Ty::Forall(_, pi), _) => Self::collect_subst_exact(pi, concrete, map),
            _ => {}
        }
    }

    fn collect_clause_vars(clause: &TClause, vars: &mut Vec<TyVar>) {
        for p in &clause.patterns { Self::collect_pattern_vars(p, vars); }
        Self::collect_expr_vars(&clause.body, vars);
        for g in &clause.guards {
            Self::collect_expr_vars(&g.condition, vars);
            Self::collect_expr_vars(&g.body, vars);
        }
        for wb in &clause.where_binds { Self::collect_expr_vars(&wb.body, vars); }
    }

    fn collect_pattern_vars(pat: &TPattern, vars: &mut Vec<TyVar>) {
        match pat {
            TPattern::Var(_, ty) => {
                for v in ty.free_vars() { if !vars.contains(&v) { vars.push(v); } }
            }
            TPattern::Constructor { args, .. } => {
                for a in args { Self::collect_pattern_vars(a, vars); }
            }
            TPattern::Paren(p) => Self::collect_pattern_vars(p, vars),
            TPattern::Tuple(ps) => { for p in ps { Self::collect_pattern_vars(p, vars); } }
            _ => {}
        }
    }

    fn collect_expr_vars(expr: &TExpr, vars: &mut Vec<TyVar>) {
        for v in expr.ty.free_vars() { if !vars.contains(&v) { vars.push(v); } }
        match &expr.kind {
            TExprKind::App(f, a) => { Self::collect_expr_vars(f, vars); Self::collect_expr_vars(a, vars); }
            TExprKind::InfixApp { lhs, rhs, .. } => { Self::collect_expr_vars(lhs, vars); Self::collect_expr_vars(rhs, vars); }
            TExprKind::Lambda { body, .. } => Self::collect_expr_vars(body, vars),
            TExprKind::If { cond, then_branch, else_branch } => {
                Self::collect_expr_vars(cond, vars);
                Self::collect_expr_vars(then_branch, vars);
                Self::collect_expr_vars(else_branch, vars);
            }
            TExprKind::Case { scrutinee, branches } => {
                Self::collect_expr_vars(scrutinee, vars);
                for b in branches {
                    for g in &b.guards {
                        Self::collect_expr_vars(&g.condition, vars);
                        Self::collect_expr_vars(&g.body, vars);
                    }
                    Self::collect_expr_vars(&b.body, vars);
                }
            }
            TExprKind::Let { binds, body } => {
                for b in binds { Self::collect_expr_vars(&b.body, vars); }
                Self::collect_expr_vars(body, vars);
            }
            TExprKind::Negate(e) | TExprKind::Paren(e) => Self::collect_expr_vars(e, vars),
            TExprKind::Tuple(es) => { for e in es { Self::collect_expr_vars(e, vars); } }
            TExprKind::RecordUpdate { record, updates, .. } => {
                Self::collect_expr_vars(record, vars);
                for (_, _, e) in updates { Self::collect_expr_vars(e, vars); }
            }
            TExprKind::OutgoingCallback { callee, .. } => Self::collect_expr_vars(callee, vars),
            TExprKind::FfiMaybeArg { value } => Self::collect_expr_vars(value, vars),
            _ => {}
        }
    }

    /// Rewrite a function to use dictionary-passing.
    fn rewrite_dict_passing_fn(&self, func: &mut TFunction) {
        let constraints = match self.fn_constraints.get(&func.name) {
            Some(cs) => cs.clone(),
            None => return,
        };
        let dict_params: Vec<(String, String)> = constraints.iter().map(|c| {
            (c.class_name.clone(), format!("__dict_{}", c.class_name))
        }).collect();
        func.dict_params = dict_params.clone();

        let class_to_dict: HashMap<String, String> = dict_params.iter()
            .map(|(cls, param)| (cls.clone(), param.clone()))
            .collect();

        let func_name = func.name.clone();
        for clause in &mut func.clauses {
            clause.body = self.rewrite_dict_expr(clause.body.clone(), &func_name, &class_to_dict);
            clause.guards = clause.guards.iter().map(|g| TGuard {
                condition: self.rewrite_dict_expr(g.condition.clone(), &func_name, &class_to_dict),
                body: self.rewrite_dict_expr(g.body.clone(), &func_name, &class_to_dict),
            }).collect();
            clause.where_binds = clause.where_binds.iter().map(|wb| TLocalDef {
                name: wb.name.clone(),
                patterns: wb.patterns.clone(),
                body: self.rewrite_dict_expr(wb.body.clone(), &func_name, &class_to_dict),
            }).collect();
        }
    }

    /// Rewrite an expression for dictionary-passing.
    fn rewrite_dict_expr(&self, expr: TExpr, func_name: &str, class_to_dict: &HashMap<String, String>) -> TExpr {
        let ty = expr.ty.clone();
        let kind = match expr.kind {
            TExprKind::Var(ref name) => {
                if let Some(class_name) = self.method_to_class.get(name)
                    && let Some(dict_param) = class_to_dict.get(class_name)
                        && self.is_polymorphic(&ty) {
                            return TExpr {
                                kind: TExprKind::DictAccess {
                                    dict_param: dict_param.clone(),
                                    method_name: name.clone(),
                                },
                                ty,
                            };
                        }
                return expr;
            }
            TExprKind::App(_, _) => {
                let (head, _) = Self::collect_app_chain(&expr);
                if let TExprKind::Var(ref call_name) = head.kind
                    && call_name == func_name {
                        let (_, args) = Self::collect_app_chain(&expr);
                        let dict_args: Vec<TExpr> = class_to_dict.values().map(|dp| {
                            TExpr::new(TExprKind::Var(dp.clone()), Ty::Unit)
                        }).collect();
                        let value_args: Vec<TExpr> = args.into_iter()
                            .map(|a| self.rewrite_dict_expr(a, func_name, class_to_dict))
                            .collect();
                        return TExpr {
                            kind: TExprKind::DictCall {
                                func_name: func_name.to_string(),
                                dict_args,
                                value_args,
                            },
                            ty,
                        };
                    }
                if let TExprKind::App(func, arg) = expr.kind {
                    TExprKind::App(
                        Box::new(self.rewrite_dict_expr(*func, func_name, class_to_dict)),
                        Box::new(self.rewrite_dict_expr(*arg, func_name, class_to_dict)),
                    )
                } else { unreachable!() }
            }
            TExprKind::InfixApp { op, lhs, rhs } => {
                if let Some(class_name) = self.method_to_class.get(&op)
                    && let Some(dict_param) = class_to_dict.get(class_name)
                        && self.is_polymorphic(&lhs.ty) {
                            let dict_access = TExpr::new(
                                TExprKind::DictAccess { dict_param: dict_param.clone(), method_name: op.clone() },
                                Ty::Unit,
                            );
                            let lhs = self.rewrite_dict_expr(*lhs, func_name, class_to_dict);
                            let rhs = self.rewrite_dict_expr(*rhs, func_name, class_to_dict);
                            let app1 = TExpr::new(TExprKind::App(Box::new(dict_access), Box::new(lhs)), Ty::Unit);
                            return TExpr::new(TExprKind::App(Box::new(app1), Box::new(rhs)), ty);
                        }
                TExprKind::InfixApp {
                    op,
                    lhs: Box::new(self.rewrite_dict_expr(*lhs, func_name, class_to_dict)),
                    rhs: Box::new(self.rewrite_dict_expr(*rhs, func_name, class_to_dict)),
                }
            }
            TExprKind::Lambda { params, body } => TExprKind::Lambda {
                params, body: Box::new(self.rewrite_dict_expr(*body, func_name, class_to_dict)),
            },
            TExprKind::If { cond, then_branch, else_branch } => TExprKind::If {
                cond: Box::new(self.rewrite_dict_expr(*cond, func_name, class_to_dict)),
                then_branch: Box::new(self.rewrite_dict_expr(*then_branch, func_name, class_to_dict)),
                else_branch: Box::new(self.rewrite_dict_expr(*else_branch, func_name, class_to_dict)),
            },
            TExprKind::Case { scrutinee, branches } => TExprKind::Case {
                scrutinee: Box::new(self.rewrite_dict_expr(*scrutinee, func_name, class_to_dict)),
                branches: branches.into_iter().map(|b| TCaseBranch {
                    pattern: b.pattern,
                    guards: b.guards.into_iter().map(|g| TGuard {
                        condition: self.rewrite_dict_expr(g.condition, func_name, class_to_dict),
                        body: self.rewrite_dict_expr(g.body, func_name, class_to_dict),
                    }).collect(),
                    body: self.rewrite_dict_expr(b.body, func_name, class_to_dict),
                }).collect(),
            },
            TExprKind::Let { binds, body } => TExprKind::Let {
                binds: binds.into_iter().map(|b| TLocalDef {
                    name: b.name, patterns: b.patterns,
                    body: self.rewrite_dict_expr(b.body, func_name, class_to_dict),
                }).collect(),
                body: Box::new(self.rewrite_dict_expr(*body, func_name, class_to_dict)),
            },
            TExprKind::Negate(e) => TExprKind::Negate(Box::new(self.rewrite_dict_expr(*e, func_name, class_to_dict))),
            TExprKind::Paren(e) => TExprKind::Paren(Box::new(self.rewrite_dict_expr(*e, func_name, class_to_dict))),
            TExprKind::Tuple(es) => TExprKind::Tuple(es.into_iter().map(|e| self.rewrite_dict_expr(e, func_name, class_to_dict)).collect()),
            TExprKind::RecordUpdate { record, updates, num_fields } => TExprKind::RecordUpdate {
                record: Box::new(self.rewrite_dict_expr(*record, func_name, class_to_dict)),
                updates: updates.into_iter().map(|(n, idx, e)| (n, idx, self.rewrite_dict_expr(e, func_name, class_to_dict))).collect(),
                num_fields,
            },
            other => other,
        };
        TExpr { kind, ty }
    }

    /// Decompose nested App into (head_function, [arg1, arg2, ...])
    fn collect_app_chain(expr: &TExpr) -> (&TExpr, Vec<TExpr>) {
        let mut args = Vec::new();
        let mut e = expr;
        while let TExprKind::App(f, a) = &e.kind {
            args.push(a.as_ref().clone());
            e = f.as_ref();
        }
        args.reverse();
        (e, args)
    }

    /// Rewrite call sites to dict-passing functions.
    fn rewrite_dict_call_sites(&self, expr: TExpr) -> TExpr {
        let ty = expr.ty.clone();
        match expr.kind {
            TExprKind::App(_, _) => {
                let (head, _) = Self::collect_app_chain(&expr);
                if let TExprKind::Var(ref call_name) = head.kind
                    && self.dict_passing_fns.contains(call_name) && !self.is_polymorphic(&ty)
                        && let Some(constraints) = self.fn_constraints.get(call_name).cloned() {
                            let (_head, args) = Self::collect_app_chain(&expr);
                            let poly_fn_ty = self.poly_fns.get(call_name).map(|f| &f.ty);
                            let dict_args: Vec<TExpr> = constraints.iter().map(|c| {
                                let concrete = self.resolve_constraint_type(
                                    &c.type_var, poly_fn_ty, &args);
                                self.build_concrete_dict(&c.class_name, &concrete)
                            }).collect();
                            let value_args: Vec<TExpr> = args.into_iter()
                                .map(|a| self.rewrite_dict_call_sites(a))
                                .collect();
                            return TExpr {
                                kind: TExprKind::DictCall {
                                    func_name: call_name.clone(),
                                    dict_args,
                                    value_args,
                                },
                                ty,
                            };
                        }
                if let TExprKind::App(func, arg) = expr.kind {
                    TExpr {
                        kind: TExprKind::App(
                            Box::new(self.rewrite_dict_call_sites(*func)),
                            Box::new(self.rewrite_dict_call_sites(*arg)),
                        ),
                        ty,
                    }
                } else { unreachable!() }
            }
            TExprKind::InfixApp { op, lhs, rhs } => TExpr {
                kind: TExprKind::InfixApp {
                    op,
                    lhs: Box::new(self.rewrite_dict_call_sites(*lhs)),
                    rhs: Box::new(self.rewrite_dict_call_sites(*rhs)),
                }, ty,
            },
            TExprKind::Lambda { params, body } => TExpr {
                kind: TExprKind::Lambda { params, body: Box::new(self.rewrite_dict_call_sites(*body)) }, ty,
            },
            TExprKind::If { cond, then_branch, else_branch } => TExpr {
                kind: TExprKind::If {
                    cond: Box::new(self.rewrite_dict_call_sites(*cond)),
                    then_branch: Box::new(self.rewrite_dict_call_sites(*then_branch)),
                    else_branch: Box::new(self.rewrite_dict_call_sites(*else_branch)),
                }, ty,
            },
            TExprKind::Case { scrutinee, branches } => TExpr {
                kind: TExprKind::Case {
                    scrutinee: Box::new(self.rewrite_dict_call_sites(*scrutinee)),
                    branches: branches.into_iter().map(|b| TCaseBranch {
                        pattern: b.pattern,
                        guards: b.guards.into_iter().map(|g| TGuard {
                            condition: self.rewrite_dict_call_sites(g.condition),
                            body: self.rewrite_dict_call_sites(g.body),
                        }).collect(),
                        body: self.rewrite_dict_call_sites(b.body),
                    }).collect(),
                }, ty,
            },
            TExprKind::Let { binds, body } => TExpr {
                kind: TExprKind::Let {
                    binds: binds.into_iter().map(|b| TLocalDef {
                        name: b.name, patterns: b.patterns,
                        body: self.rewrite_dict_call_sites(b.body),
                    }).collect(),
                    body: Box::new(self.rewrite_dict_call_sites(*body)),
                }, ty,
            },
            TExprKind::Negate(e) => TExpr {
                kind: TExprKind::Negate(Box::new(self.rewrite_dict_call_sites(*e))), ty,
            },
            TExprKind::Paren(e) => TExpr {
                kind: TExprKind::Paren(Box::new(self.rewrite_dict_call_sites(*e))), ty,
            },
            _ => expr,
        }
    }

    fn resolve_constraint_type(&self, type_var: &str, poly_fn_ty: Option<&Ty>, args: &[TExpr]) -> Ty {
        if let Some(fn_ty) = poly_fn_ty {
            let mut subst = HashMap::new();
            Self::match_fn_args(fn_ty, args, &mut subst);
            if let Some(ty) = subst.get(type_var) { return ty.clone(); }
        }
        if !args.is_empty()
            && let Some(inner) = Self::extract_inner_type(&args[0].ty) { return inner; }
        Ty::Con("_".into())
    }

    fn match_fn_args(fn_ty: &Ty, args: &[TExpr], subst: &mut HashMap<String, Ty>) {
        let mut param_ty = fn_ty;
        for arg in args {
            if let Ty::Arrow(from, to) = param_ty {
                Self::collect_subst_by_name(from, &arg.ty, subst);
                param_ty = to;
            }
        }
    }

    fn extract_inner_type(ty: &Ty) -> Option<Ty> {
        match ty {
            Ty::App(_, inner) => Some(*inner.clone()),
            Ty::List(inner) => Some(*inner.clone()),
            _ => None,
        }
    }

    fn build_concrete_dict(&self, class_name: &str, concrete_ty: &Ty) -> TExpr {
        let class_info = match self.classes.get(class_name) {
            Some(ci) => ci,
            None => return TExpr::new(TExprKind::Lit(TLiteral::Unit), Ty::Unit),
        };
        let mut method_impls = Vec::new();
        for (method_name, _) in &class_info.methods {
            // Implementations already generated for this exact type (tuple/
            // list/Maybe show and eq), then the instance registry by head.
            let impl_name = self.generated_impls
                .get(&(method_name.clone(), concrete_ty.clone()))
                .cloned()
                .or_else(|| InstHead::of(concrete_ty).and_then(|h| {
                    self.instance_methods.get(&(method_name.clone(), h)).cloned()
                }))
                .unwrap_or_else(|| method_name.clone());
            method_impls.push(format!("{}={}", method_name, impl_name));
        }
        let spec = format!("__mll_dict:{}:{}", class_name, method_impls.join(","));
        TExpr::new(
            TExprKind::SpecCall {
                original: format!("__dict_{}", class_name),
                specialized: spec,
                args: vec![],
            },
            Ty::Unit,
        )
    }
}
