-- ByteString: efficient byte sequences backed by Lua strings
--
-- All functions are intrinsic (defined in the compiler runtime).
-- Import this module for documentation; the functions are available
-- without import since they are registered as builtins.
--
-- Indices are 0-based.
--
-- Construction:
--   bsEmpty     :: ByteString
--   bsSingleton :: Int -> ByteString
--   bsCons      :: Int -> ByteString -> ByteString
--   bsSnoc      :: ByteString -> Int -> ByteString
--   bsConcat     :: ByteString -> ByteString -> ByteString
--   bsConcatList :: [ByteString] -> ByteString
--   bsReplicate  :: Int -> Int -> ByteString
--   bsPack       :: [Int] -> ByteString
--
-- Deconstruction:
--   bsHead      :: ByteString -> Int
--   bsTail      :: ByteString -> ByteString
--   bsUnpack    :: ByteString -> [Int]
--
-- Query:
--   bsLength    :: ByteString -> Int
--   bsIndex     :: ByteString -> Int -> Int
--   bsNull      :: ByteString -> Bool
--   bsSub       :: ByteString -> Int -> Int -> ByteString
--
-- Transformations:
--   bsMap       :: (Int -> Int) -> ByteString -> ByteString
--   bsFoldl     :: (a -> Int -> a) -> a -> ByteString -> a
--   bsXor       :: ByteString -> ByteString -> ByteString
--                  (result is as long as the SHORTER operand, like bsZipWith)
--   bsZipWith   :: (Int -> Int -> Int) -> ByteString -> ByteString -> ByteString
--
-- Conversion:
--   bsToString   :: ByteString -> String
--   bsFromString :: String -> ByteString
